#pragma once

const int DEFAULT_CNN_INPUT_SIZE = 28;
const int DEFAULT_CNN_CONV_FILTER_SIZE = 3;
const int DEFAULT_CNN_CONV_PADDING_SIZE = 1;
const int DEFAULT_CNN_CONV_STRIDE_SIZE = 1;
const int DEFAULT_CNN_CONV_OUTPUT_SIZE = 28;

const int DEFAULT_CNN_POOLING_INPUT_SIZE = 28;
const int DEFAULT_CNN_POOLING_FILTER_SIZE = 2;
const int DEFAULT_CNN_POOLING_STRIDE_SIZE = 2;
const int DEFAULT_CNN_POOLING_OUTPUT_SIZE = 13;

const int DEFAULT_CNN_FLATTEN_INPUT_SIZE = 13;
const int DEFAULT_CNN_OUTPUT_SIZE = 10;
